name: "HA Views Beta"
version: "0.3.0-beta.60"
slug: "ha_views"
description: "Visual Home Assistant dashboards on any background. / Wizualne pulpity Home Assistant na dowolnym tle."
url: "https://github.com/VoyteckPL/ha-views-beta"
stage: experimental
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_icon: "mdi:view-dashboard-outline"
panel_title: "HA Views"
homeassistant_api: true
map:
  - config:rw
